version: '3.6'
services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASS:-123}"
      MYSQL_DATABASE: "${DATABASE_SCHEMA:-node}"
      MYSQL_USER: "${DATABASE_USER:-node}"
      MYSQL_PASSWORD: "${DATABASE_PASS:-123}"
    ports:
      - "3306:3306"
volumes:
  db:

